import {
  Category,
  EmergencyIncident,
  EquipmentFleet,
  HeroSlideItem,
  MissionLog,
  NewsArticle,
  OfficerRoster,
  SiteConfig,
} from '@/types/database';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    slug: 'ems-accident',
    name_th: 'การแพทย์ฉุกเฉินและอุบัติเหตุทางถนน',
    name_en: 'EMS & Road Traffic Accidents',
    description: 'ออกปฏิบัติการรับ-ส่ง ปฐมพยาบาล และตัด-ถ่างช่วยชีวิต 24 ชั่วโมง',
    icon_name: 'Ambulance',
    category_type: 'mission',
    sort_order: 1,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat-2',
    slug: 'water-rescue',
    name_th: 'กู้ภัยทางน้ำและประดาน้ำค้นหา',
    name_en: 'Scuba Diving & Underwater Search',
    description: 'ชุดประดาน้ำกู้ชีพ ค้นหาผู้สูญหายใต้น้ำ และงมค้นหาทรัพย์สินของมีค่า',
    icon_name: 'Waves',
    category_type: 'mission',
    sort_order: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat-3',
    slug: 'disaster-community',
    name_th: 'บรรเทาสาธารณภัยและช่วยเหลือชุมชน',
    name_en: 'Disaster Relief & Wildlife Removal',
    description: 'จับสัตว์มีพิษ งู อสรพิษ อุทกภัยน้ำท่วม ดับเพลิงเบื้องต้น รถเสีย',
    icon_name: 'ShieldAlert',
    category_type: 'mission',
    sort_order: 3,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat-4',
    slug: 'crime-forensics',
    name_th: 'ชันสูตรพลิกศพและสนับสนุนเจ้าหน้าที่ตำรวจ',
    name_en: 'Forensics & Police Support',
    description: 'ร่วมตรวจสอบที่เกิดเหตุกับ สภ.บรบือ สภ.กุดรัง และแพทย์เวร รพ.บรบือ',
    icon_name: 'FileCheck2',
    category_type: 'mission',
    sort_order: 4,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cat-5',
    slug: 'indigent-transport',
    name_th: 'ส่งผู้ป่วยติดเตียงและผู้วายชนม์ยากไร้',
    name_en: 'Indigent Patient & Funeral Transport',
    description: 'โครงการมนุษยธรรมส่งร่างผู้วายชนม์และผู้ป่วยติดเตียงยากไร้กลับภูมิลำเนาฟรี',
    icon_name: 'HeartHandshake',
    category_type: 'mission',
    sort_order: 5,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_MISSIONS: MissionLog[] = [
  {
    id: 'mis-1',
    title: 'ภารกิจประดาน้ำร่วมค้นหาร่างผู้สูญหายจากเหตุการณ์เรือยาวชนตอม่อสะพานในแม่น้ำชี',
    category_slug: 'water-rescue',
    incident_date: '2026-02-14',
    location: 'สะพานข้ามแม่น้ำชี รอยต่อมหาสารคาม-กาฬสินธุ์',
    district: 'บรบือ - พื้นที่แม่น้ำชี',
    summary: 'ชุดปฏิบัติการประดาน้ำกู้ภัยประจิม ผนึกกำลังร่วมกับหน่วยกู้ภัยจีเสียงเกาะและกู้ภัยกาฬสินธุ์ ดำน้ำค้นหาผู้สูญหายใต้น้ำที่มีกระแสน้ำเชี่ยวจนสำเร็จ',
    details: 'ได้รับแจ้งเหตุเรือยาวประสบอุบัติเหตุชนตอม่อสะพานแม่น้ำชี มีผู้สูญหายใต้น้ำ ชุดปฏิบัติการกู้ภัยทางน้ำ หน่วยกู้ภัยประจิม สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์ นำเรือยางพร้อมชุดดำน้ำ Scuba เข้าร่วมบัญชาการเหตุการณ์และดำน้ำสแกนพื้นที่ใต้น้ำร่วมกับภาคีเครือข่าย สามารถค้นหาร่างผู้ประสบภัยและนำขึ้นฝั่งส่งมอบให้ญาติและแพทย์เวรชันสูตรอย่างสมเกียรติ',
    cover_image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    special_tag: 'ภารกิจระดับจังหวัด',
    team_lead: 'นายชัยยุทธ จิตอาสา (ประจิม 01)',
    officer_count: 8,
    views_count: 1420,
    created_at: '2026-02-14T10:00:00Z',
    updated_at: '2026-02-14T10:00:00Z',
  },
  {
    id: 'mis-2',
    title: 'ภารกิจดำน้ำงมค้นหาแหวนเพชรและของมีค่าหลักแสนบาทในบ่อน้ำลึก คืนเจ้าทุกข์',
    category_slug: 'water-rescue',
    incident_date: '2026-01-28',
    location: 'บ่อน้ำการเกษตรความลึก 6 เมตร ตำบลบรบือ',
    district: 'บรบือ',
    summary: 'ข่าวดังระดับประเทศ! เจ้าหน้าที่ชุดประดาน้ำกู้ภัยประจิม ดำน้ำงมหาแหวนเพชรและทรัพย์สินมีค่าที่คนร้ายนำมาทิ้งน้ำ คืนเจ้าของสำเร็จครบถ้วน',
    details: 'ได้รับการประสานงานจากเจ้าหน้าที่ตำรวจ สภ.บรบือ และผู้เสียหาย กรณีคนร้ายก่อเหตุแล้วนำทรัพย์สินแหวนเพชรและทองคำมูลค่ากว่า 350,000 บาทมาโยนทิ้งลงในบ่อน้ำลึก 6 เมตร ทีมประดาน้ำประจิมใช้เทคนิคค้นหาแบบ Grid Search ใต้น้ำที่มีโคลนหนาแน่น ใช้เวลา 45 นาที จึงพบแหวนเพชรและของมีค่าทั้งหมด นำส่งคืนผู้เสียหายโดยไม่คิดค่าตอบแทนใดๆ สร้างความประทับใจให้ประชาชนทั่วประเทศ',
    cover_image_url: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    special_tag: 'ภารกิจพิเศษ / ช่วยเหลือประชาชน',
    team_lead: 'นายนพรัตน์ กู้ภัยใต้น้ำ (ประจิม 05)',
    officer_count: 4,
    views_count: 2890,
    created_at: '2026-01-28T14:30:00Z',
    updated_at: '2026-01-28T14:30:00Z',
  },
  {
    id: 'mis-3',
    title: 'ปฏิบัติการเผชิญเหตุอุทกภัยฉับพลัน อพยพชาวบ้านและสัตว์เลี้ยง กรณีอ่างเก็บน้ำล้น',
    category_slug: 'disaster-community',
    incident_date: '2025-10-18',
    location: 'บ้านหนองหว้า ต.บรบือ อ.บรบือ จ.มหาสารคาม',
    district: 'บรบือ',
    summary: 'ระดมเรือท้องแบนและทีมกู้ภัยลงพื้นที่น้ำท่วมฉับพลัน ช่วยเหลืออพยพผู้สูงอายุ ผู้ป่วยติดเตียง และสัตว์เลี้ยงไปยังศูนย์พักพิงชั่วคราวอย่างปลอดภัย',
    details: 'เกิดฝนตกหนักต่อเนื่องส่งผลให้อ่างเก็บน้ำในพื้นที่ อ.บรบือ ระบายน้ำไม่ทัน น้ำไหลบ่าเข้าท่วมบ้านเรือนราษฎร กู้ภัยประจิมส่งทีมตอบโต้สาธารณภัย เรือท้องแบนติดเครื่องยนต์ รถยกสูง เข้าลำเลียงผู้สูงอายุและเด็กออกจากพื้นที่วิกฤต พร้อมแจกจ่ายน้ำดื่มและอาหารแห้งตลอด 48 ชั่วโมง',
    cover_image_url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    special_tag: 'งานบรรเทาสาธารณภัย',
    team_lead: 'นายเอกชัย ป้องกันภัย (ประจิม 02)',
    officer_count: 12,
    views_count: 1840,
    created_at: '2025-10-18T08:00:00Z',
    updated_at: '2025-10-18T08:00:00Z',
  },
  {
    id: 'mis-4',
    title: 'ตัด-ถ่างช่วยชีวิตผู้ประสบอุบัติเหตุรถยนต์ชนต้นไม้ บนถนนแจ้งสนิท สายบรบือ-มหาสารคาม',
    category_slug: 'ems-accident',
    incident_date: '2026-02-05',
    location: 'ถนนแจ้งสนิท กม.14 ต.บรบือ อ.บรบือ',
    district: 'บรบือ',
    summary: 'ปฏิบัติการใช้อุปกรณ์ตัด-ถ่างไฮดรอลิก ช่วยเหลือนำผู้ขับขี่ที่ติดภายในซากรถออกมาได้สำเร็จ และนำส่งห้องฉุกเฉิน รพ.บรบือ ภายใน 12 นาที',
    details: 'ศูนย์รับแจ้งเหตุ 1669 ส่งสัญญาณแจ้งอุบัติเหตุรถยนต์กระบะเสียหลักพุ่งชนต้นไม้ข้างทางถนนแจ้งสนิท กู้ภัยประจิมจัดชุดกู้ชีพพร้อมรถอุปกรณ์ตัด-ถ่าง ประจิม 02 เข้าถึงที่เกิดเหตุใน 5 นาที เจ้าหน้าที่ใช้เครื่องตัด-ถ่างถ่างเสาประตูเพื่อเปิดทางนำผู้บาดเจ็บส่งต่อแพทย์เวร รพ.บรบือ พ้นขีดอันตราย',
    cover_image_url: 'https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    special_tag: 'EMS การแพทย์ฉุกเฉิน',
    team_lead: 'นายวีระศักดิ์ เวชกรฉุกเฉิน',
    officer_count: 6,
    views_count: 980,
    created_at: '2026-02-05T21:15:00Z',
    updated_at: '2026-02-05T21:15:00Z',
  },
  {
    id: 'mis-5',
    title: 'โครงการสงเคราะห์: ส่งร่างผู้วายชนม์และเคลื่อนย้ายผู้ป่วยติดเตียงยากไร้กลับภูมิลำเนาฟรี',
    category_slug: 'indigent-transport',
    incident_date: '2026-02-18',
    location: 'จาก รพ.บรบือ ไปยัง อ.นาดูน และ อ.วาปีปทุม',
    district: 'บรบือ - นาดูน',
    summary: 'ดำเนินการส่งร่างผู้วายชนม์ผู้ยากไร้กลับสู่ภูมิลำเนาเพื่อประกอบพิธีทางศาสนา พร้อมเคลื่อนย้ายผู้ป่วยติดเตียงโดยไม่คิดค่าใช้จ่ายใดๆ ทั้งสิ้น',
    details: 'สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์ ให้บริการรถพยาบาลส่งร่างผู้วายชนม์ไร้ญาติหรือครอบครัวยากจนกลับสู่ภูมิลำเนา พร้อมทั้งเคลื่อนย้ายผู้ป่วยติดเตียงที่ไม่มีทุนทรัพย์กลับไปพักฟื้นที่บ้านตามเจตนารมณ์การกุศลของสมาคม',
    cover_image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    special_tag: 'งานสังคมสงเคราะห์',
    team_lead: 'นายประเสริฐ จิตเมตตา',
    officer_count: 3,
    views_count: 650,
    created_at: '2026-02-18T11:00:00Z',
    updated_at: '2026-02-18T11:00:00Z',
  },
  {
    id: 'mis-6',
    title: 'ช่วยเหลือประชาชนจับงูจงอางความยาว 3.5 เมตร เข้าบ้านเรือนประชาชน ต.บรบือ',
    category_slug: 'disaster-community',
    incident_date: '2026-02-19',
    location: 'หมู่ 4 ตำบลบรบือ อำเภอบรบือ',
    district: 'บรบือ',
    summary: 'เจ้าหน้าที่ชุดจับอสรพิษกู้ภัยประจิมใช้อุปกรณ์จับงูความปลอดภัยสูง ควบคุมงูจงอางขนาดใหญ่และนำไปปล่อยคืนสู่ผืนป่าธรรมชาติที่ห่างไกลชุมชน',
    details: 'รับแจ้งจากประชาชนว่าพบงูขนาดใหญ่เลื้อยเข้าไปหลบอยู่ใต้ถุนบ้านพัก เจ้าหน้าที่ชุดชำนาญการจับสัตว์มีพิษพร้อมอุปกรณ์เฉพาะทางเข้าตรวจสอบและควบคุมงูจงอางได้อย่างปลอดภัย ไม่มีผู้ใดได้รับอันตราย พร้อมให้คำแนะนำวิธีป้องกันสัตว์มีพิษแก่ชาวบ้าน',
    cover_image_url: 'https://images.unsplash.com/photo-1531386151447-fd76ad50012f?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    special_tag: 'ช่วยเหลือสัตว์มีพิษ ฟรี',
    team_lead: 'นายสมชาย นักจับอสรพิษ',
    officer_count: 2,
    views_count: 1120,
    created_at: '2026-02-19T16:20:00Z',
    updated_at: '2026-02-19T16:20:00Z',
  },
];

export const INITIAL_NEWS: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'ประกาศ: หน่วยกู้ภัยประจิม ย้ำเตือนประชาชน อุบัติเหตุและเจ็บป่วยฉุกเฉิน (EMS) บริการฟรี 100% ไม่มีค่าใช้จ่าย',
    summary: 'สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์ ชี้แจงเกณฑ์การให้บริการฉุกเฉิน 24 ชั่วโมง เพื่อความโปร่งใสและสร้างความมั่นใจแก่พี่น้องประชาชน',
    content: 'ตามที่สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์ (หน่วยกู้ภัยประจิม) ได้รับการสนับสนุนจากสถาบันการแพทย์ฉุกเฉินแห่งชาติ (สพฉ.) และ รพ.บรบือ ขอประชาสัมพันธ์ว่า การรับ-ส่งผู้ป่วยฉุกเฉิน ปฐมพยาบาล และอุบัติเหตุบนท้องถนนเป็น "บริการฟรีตลอด 24 ชั่วโมง" ประชาชนสามารถโทรแจ้ง 1669 หรือ 061-119-3342 ได้ทันทีโดยไม่มีการเรียกเก็บเงินใดๆ ทั้งสิ้น',
    cover_image_url: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=1200&q=80',
    published_date: '2026-02-15',
    is_pinned: true,
    author_name: 'ศูนย์ประชาสัมพันธ์ สมาคมประจิมสารคาม',
    created_at: '2026-02-15T09:00:00Z',
    updated_at: '2026-02-15T09:00:00Z',
  },
  {
    id: 'news-2',
    title: 'กู้ภัยประจิม ร่วมพิธีบวงสรวง "พ่อปู่จูมคำ" สิ่งศักดิ์สิทธิ์คู่บ้านคู่เมืองอำเภอบรบือ เสริมสิริมงคลก่อนออกปฏิบัติหน้าที่',
    summary: 'คณะกรรมการ เจ้าหน้าที่ และอาสาสมัครกู้ภัยประจิม ร่วมพิธีสักการะพ่อปู่จูมคำ ขอพรคุ้มครองการทำงานกู้ชีพกู้ภัยให้แคล้วคลาดปลอดภัย',
    content: 'เมื่อเร็วๆ นี้ คณะเจ้าหน้าที่และอาสาสมัครกู้ภัยประจิม ได้พร้อมใจกันประกอบพิธีถวายเครื่องสักการะบวงสรวง ณ ศาลพ่อปู่จูมคำ สิ่งศักดิ์สิทธิ์คู่บ้านคู่เมืองบรบือ เพื่อความเป็นสิริมงคลและสร้างขวัญกำลังใจในการอุทิศตนเพื่อสังคมและการช่วยเหลือประชาชนตลอด 24 ชั่วโมง',
    cover_image_url: 'https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?auto=format&fit=crop&w=1200&q=80',
    published_date: '2026-02-10',
    is_pinned: false,
    author_name: 'ฝ่ายบริหาร สมาคมประจิมสารคาม',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'news-3',
    title: 'เพิ่มศักยภาพชุดประดาน้ำและอุปกรณ์ตัด-ถ่าง เตรียมพร้อมรับมือเทศกาลและการเดินทางบนถนนแจ้งสนิท',
    summary: 'ตรวจเช็คความพร้อมของรถกู้ชีพ เรือตรวจการณ์ และชุดตัด-ถ่างไฮดรอลิก เพื่อให้สามารถเข้าถึงที่เกิดเหตุได้ภายใน 5-8 นาที',
    content: 'หน่วยกู้ภัยประจิมได้ทำการซักซ้อมแผนเผชิญเหตุทางน้ำและอุบัติเหตุหมู่ พร้อมตรวจเช็คบำรุงรักษาอุปกรณ์ตัด-ถ่าง ถังออกซิเจนดำน้ำ และยานพาหนะทุกคัน ณ ที่ตั้งสำนักงานถนนแจ้งสนิท เพื่อให้พร้อมบริการพี่น้องประชาชนตลอด 24 ชม.',
    cover_image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    published_date: '2026-01-20',
    is_pinned: false,
    author_name: 'ฝ่ายยุทธการและฝึกอบรม',
    created_at: '2026-01-20T14:00:00Z',
    updated_at: '2026-01-20T14:00:00Z',
  },
];

export const INITIAL_INCIDENTS: EmergencyIncident[] = [
  {
    id: 'inc-101',
    incident_number: 'PCM-2026-0042',
    caller_name: 'คุณสมศักดิ์ วงศ์มณี',
    caller_phone: '081-456-7890',
    incident_type: 'ems_traffic',
    urgency_level: 'critical',
    location_name: 'หน้าโรงเรียนบรบือวิทยาคาร ถนนแจ้งสนิท',
    district: 'อำเภอบรบือ',
    province: 'จังหวัดมหาสารคาม',
    latitude: 16.035412,
    longitude: 103.125432,
    victim_count: 2,
    details: 'รถจักรยานยนต์ชนกับรถกระบะ มีผู้บาดเจ็บนอนหมดสติ 1 ราย และแผลเปิดที่ศีรษะ 1 ราย',
    status: 'en_route',
    assigned_unit: 'ประจิม 01 (กู้ชีพฉุกเฉิน)',
    responder_notes: 'เจ้าหน้าที่ EMT กำลังออกเดินทาง คาดถึงที่เกิดเหตุใน 4 นาที',
    reported_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-102',
    incident_number: 'PCM-2026-0041',
    caller_name: 'คุณวิภาวรรณ สุขสม',
    caller_phone: '089-778-9901',
    incident_type: 'snake_wildlife',
    urgency_level: 'urgent',
    location_name: 'บ้านเลขที่ 88 หมู่ 3 ต.บรบือ (ใกล้ รพ.บรบือ)',
    district: 'อำเภอบรบือ',
    province: 'จังหวัดมหาสารคาม',
    latitude: 16.041234,
    longitude: 103.131102,
    victim_count: 0,
    details: 'พบงูเห่าขดตัวอยู่ใต้เครื่องซักผ้าหลังบ้าน ขอเจ้าหน้าที่ช่วยจับด่วน',
    status: 'on_scene',
    assigned_unit: 'ประจิม 04 (ชุดจับสัตว์มีพิษ)',
    responder_notes: 'เจ้าหน้าที่ถึงที่เกิดเหตุแล้ว กำลังใช้อุปกรณ์เข้าควบคุมงู',
    reported_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-103',
    incident_number: 'PCM-2026-0040',
    caller_name: 'คุณประสิทธิ์ ใจมั่น',
    caller_phone: '086-112-3344',
    incident_type: 'water_rescue',
    urgency_level: 'standard',
    location_name: 'อ่างเก็บน้ำหนองบ่อ อ.บรบือ',
    district: 'อำเภอบรบือ',
    province: 'จังหวัดมหาสารคาม',
    latitude: 16.028911,
    longitude: 103.119455,
    victim_count: 0,
    details: 'ชาวบ้านทำกระเป๋าสตางค์และกุญแจรถยนต์ตกน้ำขณะหาปลา ขอความช่วยเหลือทีมดำน้ำ',
    status: 'resolved',
    assigned_unit: 'ประจิม 03 (ชุดประดาน้ำ)',
    responder_notes: 'งมค้นหากุญแจและส่งมอบคืนเจ้าของเรียบร้อย',
    reported_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_FLEET: EquipmentFleet[] = [
  {
    id: 'flt-1',
    call_sign: 'ประจิม 01',
    equipment_type: 'ambulance_ems',
    name_th: 'รถพยาบาลกู้ชีพฉุกเฉิน Advance Life Support (ALS)',
    plate_number: 'นข-4412 มหาสารคาม',
    status: 'dispatched',
    location_base: 'ศูนย์ใหญ่ ถนนแจ้งสนิท อ.บรบือ',
    specifications: 'อุปกรณ์ช่วยชีวิตขั้นสูง, เครื่อง Defibrillator/AED, ออกซิเจนแรงดันสูง, เปลตัก Scooper, ชุด Splint ดามกระดูก',
    image_url: 'https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&w=1200&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'flt-2',
    call_sign: 'ประจิม 02',
    equipment_type: 'rescue_truck',
    name_th: 'รถตรวจการณ์กู้ภัยและอุปกรณ์ตัด-ถ่างไฮดรอลิก',
    plate_number: 'ผข-8890 มหาสารคาม',
    status: 'available',
    location_base: 'ศูนย์ใหญ่ ถนนแจ้งสนิท อ.บรบือ',
    specifications: 'ชุดเครื่องมือตัด-ถ่างไฮดรอลิก Holmatro, สปอตไลท์ส่องสว่างสนาม, รอกสลิงลากจูง, เลื่อยยนต์',
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'flt-3',
    call_sign: 'ประจิม 03',
    equipment_type: 'boat_scuba',
    name_th: 'เรือกู้ภัยท้องแบนติดเครื่องยนต์และชุดประดาน้ำ Scuba',
    plate_number: 'ปจ-03 (เรือประจำการ)',
    status: 'available',
    location_base: 'หน่วยปฏิบัติการทางน้ำ อ.บรบือ',
    specifications: 'เรืออลูมิเนียมกู้ภัยท้องแบน, เครื่องยนต์เรือ 40HP, ถังอากาศ Scuba 6 ชุด, เสื้อ BCD, เข็มทิศและไฟฉายใต้น้ำ',
    image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'flt-4',
    call_sign: 'ประจิม 04',
    equipment_type: 'hydraulic_cutter',
    name_th: 'รถเคลื่อนที่เร็วช่วยเหลือสาธารณภัยและจับสัตว์มีพิษ',
    plate_number: 'บน-5561 มหาสารคาม',
    status: 'available',
    location_base: 'จุดบริการวาปีปทุม - นาดูน',
    specifications: 'คีมจับงู safety, กล่องเก็บสัตว์มีพิษ, ถังดับเพลิงเคมี, เครื่องสูบน้ำไดโว่, อุปกรณ์พ่วงแบตเตอรี่',
    image_url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1200&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_OFFICERS: OfficerRoster[] = [
  {
    id: 'off-1',
    officer_code: 'PCM-01',
    full_name: 'นายชัยยุทธ ศิริวัฒน์',
    role_title: 'ประธานสมาคม / หัวหน้าชุดสั่งการกู้ภัยประจิม',
    phone: '061-119-3342',
    station_base: 'ศูนย์ใหญ่บรบือ',
    is_on_duty: true,
    joined_date: '2015-06-01',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'off-2',
    officer_code: 'PCM-02',
    full_name: 'นายกิตติศักดิ์ พรหมดี',
    role_title: 'หัวหน้าชุดปฏิบัติการกู้ชีพฉุกเฉิน (EMT-B)',
    phone: '081-234-5678',
    station_base: 'ศูนย์ใหญ่บรบือ',
    is_on_duty: true,
    joined_date: '2018-03-15',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'off-3',
    officer_code: 'PCM-03',
    full_name: 'นายนพรัตน์ แสนสุข',
    role_title: 'หัวหน้าชุดปฏิบัติการกู้ภัยทางน้ำและประดาน้ำ',
    phone: '089-876-5432',
    station_base: 'หน่วยทางน้ำบรบือ',
    is_on_duty: true,
    joined_date: '2019-11-20',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'off-4',
    officer_code: 'PCM-04',
    full_name: 'นายอนุชา พงษ์ไทย',
    role_title: 'เจ้าหน้าที่กู้ภัยตัด-ถ่างและตอบโต้สาธารณภัย',
    phone: '086-555-4321',
    station_base: 'จุดบริการวาปีปทุม',
    is_on_duty: true,
    joined_date: '2021-04-10',
    photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_SITE_CONFIG: SiteConfig = {
  org_name_th: 'หน่วยกู้ภัยประจิม',
  org_name_en: 'Prachim Rescue Association',
  association_name: 'สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์',
  slogan: 'ช่วยเหลือผู้ประสบภัย อุทิศตนเพื่อมวลชน 24 ชั่วโมง ฟรีเพื่อมนุษยธรรม',
  hotline_primary: '061-119-3342',
  hotline_secondary: '081-234-5678',
  hotline_ems: '1669',
  address_line1: 'ถนนแจ้งสนิท ตำบลบรบือ อำเภอบรบือ',
  address_line2: 'จังหวัดมหาสารคาม 44130',
  radio_frequency: '168.275 MHz (ช่องความถี่กู้ภัยประจิม)',
  license_number: 'เลขทะเบียนสมาคม มค. 4/2558',
  facebook_name: 'หน่วยกู้ภัยประจิม สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์',
  facebook_url: 'https://www.facebook.com/search/top?q=หน่วยกู้ภัยประจิม+บรบือ',
  line_id: '@prachimrescue',
  line_url: 'https://line.me/R/ti/p/@prachimrescue',
  tiktok_handle: '@prachimrescue',
  tiktok_url: 'https://www.tiktok.com/@prachimrescue',
  youtube_name: 'หน่วยกู้ภัยประจิม Official Channel',
  youtube_url: 'https://www.youtube.com/results?search_query=หน่วยกู้ภัยประจิม+บรบือ',
  google_maps_url: 'https://www.google.com/maps/search/?api=1&query=16.0375,103.1186+(หน่วยกู้ภัยประจิม+บรบือ)',
  latitude: 16.0375,
  longitude: 103.1186,
  bank_name: 'ธนาคารกรุงไทย (Krungthai Bank)',
  bank_account_name: 'สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์',
  bank_account_number: '438-0-12345-6',
  promptpay_id: '0993000123456',
  donation_notice: 'เงินบริจาคทุกบาทใช้สำหรับค่าน้ำมันรถกู้ชีพ ค่ายาเวชภัณฑ์ และอุปกรณ์กู้ภัยตัด-ถ่าง โดยไม่หักค่าใช้จ่ายส่วนตัวใดๆ',
  sacred_patron_title: 'องค์พ่อปู่จูมคำ พระผู้เปี่ยมด้วยเมตตามหาบารมี',
  sacred_patron_story: 'พ่อปู่จูมคำ เป็นศูนย์รวมจิตใจอันศักดิ์สิทธิ์ของชาวอำเภอบรบือและอาสาสมัครกู้ภัยประจิมทุกคน เป็นมิ่งขวัญคุ้มครองความปลอดภัยในการออกช่วยเหลือเพื่อนมนุษย์',
};

export const INITIAL_HERO_SLIDES: HeroSlideItem[] = [
  {
    id: 'slide-1',
    badge: 'การแพทย์ฉุกเฉินและอุบัติเหตุทางถนน 24 ชม.',
    title_line1: 'เข้าถึงรวดเร็ว. กู้ชีพฉุกเฉิน.',
    title_line2: 'ช่วยเหลือทุกชีวิต ปลอดภัย.',
    subtitle: 'หน่วยกู้ภัยประจิม (สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์) พร้อมทีมกู้ชีพ EMT-B รถพยาบาลกู้ชีพ และอุปกรณ์ตัด-ถ่างไฮดรอลิก ดูแลประชาชนบนถนนแจ้งสนิทและทั่วอำเภอบรบือ ตลอด 24 ชั่วโมง ฟรี 100%',
    cover_image: 'https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&w=1920&q=80',
    icon_name: 'Ambulance',
    stat1_val: '< 8 นาที',
    stat1_lbl: 'เวลาตอบสนองเฉลี่ย',
    stat2_val: 'ฟรี 100%',
    stat2_lbl: 'บริการอุบัติเหตุ EMS',
    stat3_val: '24 ชั่วโมง',
    stat3_lbl: 'ปฏิบัติการต่อเนื่อง',
    primary_btn_text: 'แจ้งเหตุด่วนฉุกเฉิน',
    primary_btn_action: 'report',
    secondary_btn_text: 'โทร 061-119-3342',
    secondary_btn_url: 'tel:0611193342',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'slide-2',
    badge: 'ชุดปฏิบัติการกู้ภัยทางน้ำและประดาน้ำระดับจังหวัด',
    title_line1: 'ชุดประดาน้ำกู้ภัย.',
    title_line2: 'ค้นหาใต้น้ำ & ช่วยเหลือผู้ประสบภัย.',
    subtitle: 'ภารกิจดำน้ำค้นหาผู้สูญหายในแม่น้ำชี อ่างเก็บน้ำ และคลองชลประทาน พร้อมผลงานเด่นดำน้ำค้นหาแหวนเพชรและทรัพย์สินมีค่าคืนเจ้าทุกข์สำเร็จ สร้างชื่อเสียงระดับประเทศ',
    cover_image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1920&q=80',
    icon_name: 'Waves',
    stat1_val: 'มาตรฐานกู้ชีพ',
    stat1_lbl: 'นักประดาน้ำ Scuba',
    stat2_val: 'ฟรีเพื่อมนุษยธรรม',
    stat2_lbl: 'ภารกิจใต้น้ำ',
    stat3_val: 'พร้อมลงพื้นที่',
    stat3_lbl: 'เรือกู้ภัยท้องแบน',
    primary_btn_text: 'ดูผลงานประดาน้ำ',
    primary_btn_action: 'missions',
    secondary_btn_text: 'ขอความช่วยเหลือกู้ภัยทางน้ำ',
    secondary_btn_url: 'tel:0611193342',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'slide-3',
    badge: 'งานบรรเทาสาธารณภัยและช่วยเหลือชุมชน',
    title_line1: 'เผชิญเหตุสาธารณภัย.',
    title_line2: 'จับสัตว์มีพิษ & อพยพน้ำท่วม.',
    subtitle: 'พร้อมทีมเฉพาะทางจับอสรพิษ งูเห่า งูจงอาง สัตว์มีพิษเข้าบ้านเรือน บริการช่วยเหลือรถเสีย แบตหมด ดับเพลิงเบื้องต้น และภารกิจอพยพผู้ประสบอุทกภัยในพื้นที่บรบือ',
    cover_image: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1920&q=80',
    icon_name: 'ShieldAlert',
    stat1_val: 'ฟรี ไม่มีค่าใช้จ่าย',
    stat1_lbl: 'จับสัตว์มีพิษ/งู',
    stat2_val: 'Safety 100%',
    stat2_lbl: 'อุปกรณ์เฉพาะทาง',
    stat3_val: 'จิตอาสา 24 ชม.',
    stat3_lbl: 'ช่วยเหลือชุมชน',
    primary_btn_text: 'แจ้งจับงู / สัตว์มีพิษ',
    primary_btn_action: 'report',
    secondary_btn_text: 'โทรสายตรง 061-119-3342',
    secondary_btn_url: 'tel:0611193342',
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'slide-4',
    badge: 'ศูนย์ประสานงานเครือข่าย 1669 มหาสารคาม',
    title_line1: 'บารมี "พ่อปู่จูมคำ".',
    title_line2: 'อุทิศตนเพื่อสังคม บรบือสารคาม.',
    subtitle: 'สมาคมประจิมสารคาม พุทธศาสตร์สงเคราะห์ น้อมนำคุณธรรมช่วยเหลือผู้ยากไร้ ส่งผู้ป่วยติดเตียงและผู้วายชนม์กลับภูมิลำเนาฟรี ประสานงานร่วมกับ รพ.บรบือ สภ.บรบือ และศูนย์สั่งการ 1669',
    cover_image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1920&q=80',
    icon_name: 'LifeBuoy',
    stat1_val: 'พ่อปู่จูมคำ',
    stat1_lbl: 'สิ่งศักดิ์สิทธิ์คู่บ้าน',
    stat2_val: 'ฟรีสงเคราะห์',
    stat2_lbl: 'ส่งผู้วายชนม์ยากไร้',
    stat3_val: 'บรบือ-วาปี-นาดูน',
    stat3_lbl: 'จุดบริการเครือข่าย',
    primary_btn_text: 'ทำความรู้จักหน่วยงาน',
    primary_btn_action: 'contact',
    secondary_btn_text: 'ร่วมสนับสนุนสมาคม',
    secondary_btn_url: '#section-about',
    is_active: true,
    sort_order: 4,
  },
];

